### ISSUE TITLE
Icon search on website not proper

### ISSUE THREAD

**Issue by RivanParmar** [ericcornelissen/tmp#193] opened 2022-03-17 08:52 UTC
- [ ] Feature
- [x] Bug
- [ ] Design
- [ ] Other, namely:

### Description
When searching for icons on the Simpleicons.org website, the website shows icons that aren't relevant to the search at all. For example while searching for Adobe the list of icons show Academia, Adblock, Blackberry, etc. along with Adobe. This should not happen. If searching Adobe then only icons with the name having Adobe should be shown.

**Comment by mondeja** [comment] 2022-03-17 12:04
Thanks, duplicate of #186.

**Closed as completed by mondeja** 2022-03-17 12:04 UTC

**Comment by mondeja** [comment] 2022-03-17 20:47
It is fixed now, cheers! ✋🏼
