### ISSUE TITLE
Why is SimpleIcons website slow? Are there any plans on improving performance?

### ISSUE THREAD

**Issue by AmodeusR** [ericcornelissen/tmp#200] opened 2022-04-20 18:36 UTC
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [ ] Design
- [x] Other, namely: Performance

### Description

Whenever I try to use Simple Icons website, it always freeze seconds after I enter in it. I can scroll up and down, but I can't type in the field search or click on the icons to download or anything.

I use Chrome, by the way. I tested in Firefox and it worked better, it didn't freeze and such, though it still were a little bit slow.

 Are there any plans for improving performance? Because it seems SimpleIcons website really needs a performance boost.

**Comment by mondeja** [comment] 2022-04-20 22:21
We're receiving these type of reports but we can't reproduce it.

I've tested manually on Firefox, Chrome and Safari and works well for me. but I've 4 cores and 8 Gbs of RAM, what are the specifications of your device? Do you're able to share a performance record?

**Comment by AmodeusR** [comment] 2022-04-22 22:46
I have a AMD Athlon 3000G, 2 cores & 4 thread and 16GB of Ram. Surely the problem is in the cpu, since I have plenty of RAM, and seeing the performance profiler from firefox, cpu usage goes to almost 90% in certain moments.

I can't run the test on chrome if I'm using the normal browsing option, probably because of the extensions I have. Doing it in anonymous mode I could run the test. The initial experience is bad, getting very slow and even freezing, but after it's all loaded, it works normally, which in Firefox, it worked better from the get go but still stutter along the way.

Heres the Firefox performance map: https://share.firefox.dev/36EfB4P
Here's the Chrome's performance map: https://we.tl/t-9I8ls9JWmD

Chrome's test will be available for download for 1 week, but I think it's enough time to take a look at it.

If I would to guess what could be causing the problem, I would consider the fact is loads every icon in the main page. Maybe creating a pagination, or a infinite scroll with a defined number os icons to be loaded could considerably improve UX in lower end computers, but this is just a guess.

**Comment by wang1212** [comment] 2022-04-23 15:58
I have the same problem. However, when I open the page in **Chrome's private mode**, the page loads quickly and all the problems are gone.

---

After my testing, I found that some extensions I had installed were causing this problem, closing the extension and closing the browser, then reopening the browser and opening the web page returned to normal.

- [Wappalyzer - Technology profiler](https://chrome.google.com/webstore/detail/wappalyzer-technology-pro/gppongmhjkpfnbhagpmjfkannfbllamg)
- [JSON-handle](https://chrome.google.com/webstore/detail/json-handle/iahnhfdhidomcpggpaimmmahffihkfnj)

---
win10, chrome 102.0.5005.12 (dev 64)

**Comment by mondeja** [comment] 2022-04-24 19:39
> If I would to guess what could be causing the problem, I would consider the fact is loads every icon in the main page. Maybe creating a pagination, or a infinite scroll with a defined number os icons to be loaded could considerably improve UX in lower end computers, but this is just a guess.

I can see in the Firefox performance map that indeed it is loading a hundred of icons. We've implemented lazy loading using [the attribute `loading="lazy"`](https://github.com/simple-icons/simple-icons-website/blob/0fe36317227f2bc019f14aae5ff07a4af6040d5c/public/index.pug#L330) so this should not happen, the icons should load only if they appear on the screen. Is your screen so big that so many icons appear when you load the page @AmodeusR? Could you confirm that other extensions are not interfering, maybe because are loading the images without respecting the `loading` attribute?

**Comment by AmodeusR** [comment] 2022-04-27 15:21
> Is your screen so big that so many icons appear when you load the page?

Not really, it's just a 1920x1080 monitor, it doesn't show up so many icons.

 But I think what Wang said is probably the case, since when I browse the website in incognito mode it works 90% as expected, and I also have Wappalyzer.

Nevertheless, it is still heavy, because I don't have extensions in the Firefox browser but still the tests showed it used up to 90% of CPU usage for some time, so I think there still room for improvements.

**Comment by mondeja** [comment] 2022-04-27 20:19
> Nevertheless, it is still heavy, because I don't have extensions in the Firefox browser but still the tests showed it used up to 90% of CPU usage for some time, so I think there still room for improvements.

Definitely, but unless you've a concrete proposal, I'm closing this to keep the issue tracker clean.

**Closed as completed by mondeja** 2022-04-27 20:19 UTC

**Comment by SimonGolms** [comment] 2022-08-08 08:15
> I have the same problem. However, when I open the page in **Chrome's private mode**, the page loads quickly and all the problems are gone.
> 
> After my testing, I found that some extensions I had installed were causing this problem, closing the extension and closing the browser, then reopening the browser and opening the web page returned to normal.

That was the right hint and in my case it was the chrome extension [`META SEO inspector`](https://chrome.google.com/webstore/detail/meta-seo-inspector/ibkclpciafdglkjkcibmohobjkcfkaef) which slowed down the page. I solved it by changing the site access permissions from `On all sites` to `On click`.
