### ISSUE TITLE
Your website is killing the browser

### ISSUE THREAD

**Issue by creotip** [ericcornelissen/tmp#161] opened 2021-12-17 12:32 UTC
While scrolling the page, the browser is extremely overloaded :
https://simpleicons.org/

Use virtualization technique for lazy loading

**Comment by mondeja** [comment] 2021-12-17 13:21
Duplicate of #143

**Comment by jorgeamadosoria** [comment] 2021-12-17 20:24
> 
@creotip thanks for the report. We are already using lazy loading for the images. 

Is this on a computer or mobile? Which browser are you using? if the problem you see is on mobile, we have an issue for that already #143 in which we are working on.

If you have a code suggestion, do you think you can make a contribution to the project with your solution? That would help you get the features you want faster.

**Comment by creotip** [comment] 2021-12-22 09:14
@jorgeamadosoria Using chrome on MAC:

See the chrome task manager. Simple icons website consume too much CPU
![Screen Shot 2021-12-22 at 11 12 18](https://user-images.githubusercontent.com/3135968/147067787-cd8bbe62-5e09-4c6c-bf4e-faf5316f40c0.png)

**Comment by mondeja** [comment] 2021-12-22 18:47
I can reproduce it using different browsers. See the next demo (Chrome):

![lazy-loading-base64-bug](https://user-images.githubusercontent.com/23049315/147140583-ad6e8377-e22a-4b6f-8e65-3d1907a748c3.gif)

It seems that we're not using real lazy loading because browsers don't support lazy loading for images injected as base64 data.

**Comment by creotip** [comment] 2021-12-22 18:58
There is several techniques to solve it, even if the images are base64. One of the techniques is to leverage intersection observer api

**Comment by mondeja** [comment] 2021-12-22 19:01
I think that here we can just use the relative path to the icons, so we don't need to use external libraries and will work even if the user has Javascript disabled. FYI and to give a bit of background, this should has been solved by #55 but it seems that it was not.

**Comment by creotip** [comment] 2021-12-22 19:03
I would re-write the website using gatsby or next.js

In gatsby there is gatsby-plugin-image, which is one the best implementation of lazy loading images, as well as compression, resize and placeholders. also the architecture is perfect for simple-icons web app

**Comment by mondeja** [comment] 2021-12-22 19:04
This has been discussed several times in the past. Personally I'm against it. If you want to discuss it, feel free to open another issue.

**Comment by jorgeamadosoria** [comment] 2021-12-24 19:56
> I would re-write the website using gatsby or next.js
> 
> In gatsby there is gatsby-plugin-image, which is one the best implementation of lazy loading images, as well as compression, resize and placeholders. also the architecture is perfect for simple-icons web app

me too, but as @mondeja said, it has been discussed and there are arguments pro and con. Regardless of that discussion, the website won't be rewritten in any other tech stack for at least one more year. I'm afraid we will have to solve this issue with more base technology.

**Closed as completed** 2021-12-25 23:00 UTC
Labels: bug
